services:
  - type: web
    name: scraper-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn scraper_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
